# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TingBa' do
pod 'AFNetworking'
pod 'SDCycleScrollView'
pod 'MBProgressHUD'
pod 'FMDB'
pod 'RESideMenu'
pod 'SVProgressHUD'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TingBa

  target 'TingBaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TingBaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
